# Generated by Django 5.0.4 on 2026-03-26 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clazz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='PascalCase class name, e.g. PropertyImage', max_length=100, unique=True)),
                ('verbose_name', models.CharField(blank=True, max_length=200)),
                ('verbose_name_plural', models.CharField(blank=True, max_length=200)),
                ('app_label', models.CharField(blank=True, help_text='Optional – override app_label in Meta', max_length=100)),
                ('db_table', models.CharField(blank=True, help_text='Optional – override table name', max_length=100)),
                ('ordering', models.CharField(blank=True, help_text='Comma-separated fields, e.g. -created_at,name', max_length=200)),
                ('abstract', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text='Internal notes / description')),
                ('list_display', models.TextField(blank=True, help_text='Comma-separated field names to show in list view')),
                ('search_fields', models.TextField(blank=True, help_text='Comma-separated field names to search on')),
                ('list_filter', models.TextField(blank=True, help_text='Comma-separated field names for sidebar filter')),
                ('date_hierarchy', models.CharField(blank=True, help_text='Single DateField/DateTimeField for drill-down', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clazz',
                'verbose_name_plural': 'Clazzes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Python attribute name, e.g. first_name', max_length=100)),
                ('verbose_name', models.CharField(blank=True, max_length=200)),
                ('field_type', models.CharField(choices=[('CharField', 'CharField – short text'), ('TextField', 'TextField – long text'), ('SlugField', 'SlugField'), ('EmailField', 'EmailField'), ('URLField', 'URLField'), ('UUIDField', 'UUIDField'), ('GenericIPAddressField', 'GenericIPAddressField'), ('IntegerField', 'IntegerField'), ('PositiveIntegerField', 'PositiveIntegerField'), ('BigIntegerField', 'BigIntegerField'), ('SmallIntegerField', 'SmallIntegerField'), ('FloatField', 'FloatField'), ('DecimalField', 'DecimalField'), ('BooleanField', 'BooleanField'), ('NullBooleanField', 'NullBooleanField (deprecated, use BooleanField+null=True)'), ('DateField', 'DateField'), ('DateTimeField', 'DateTimeField'), ('TimeField', 'TimeField'), ('DurationField', 'DurationField'), ('FileField', 'FileField'), ('ImageField', 'ImageField'), ('FilePathField', 'FilePathField'), ('ForeignKey', 'ForeignKey'), ('OneToOneField', 'OneToOneField'), ('ManyToManyField', 'ManyToManyField'), ('JSONField', 'JSONField'), ('BinaryField', 'BinaryField'), ('AutoField', 'AutoField'), ('BigAutoField', 'BigAutoField')], default='CharField', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('null', models.BooleanField(default=False)),
                ('blank', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
                ('db_index', models.BooleanField(default=False)),
                ('primary_key', models.BooleanField(default=False)),
                ('editable', models.BooleanField(default=True)),
                ('max_length', models.PositiveIntegerField(blank=True, help_text='Required for CharField/SlugField/etc.', null=True)),
                ('default', models.CharField(blank=True, help_text='Leave blank for no default; use "None" for explicit None', max_length=500)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('choices', models.TextField(blank=True, help_text='One choice per line: VALUE,Label')),
                ('max_digits', models.PositiveIntegerField(blank=True, null=True)),
                ('decimal_places', models.PositiveIntegerField(blank=True, null=True)),
                ('auto_now', models.BooleanField(default=False)),
                ('auto_now_add', models.BooleanField(default=False)),
                ('related_name', models.CharField(blank=True, help_text='related_name argument', max_length=100)),
                ('on_delete', models.CharField(blank=True, choices=[('CASCADE', 'CASCADE'), ('PROTECT', 'PROTECT'), ('SET_NULL', 'SET_NULL'), ('SET_DEFAULT', 'SET_DEFAULT'), ('DO_NOTHING', 'DO_NOTHING')], default='CASCADE', help_text='on_delete for FK/O2O', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='builder.clazz')),
                ('related_clazz', models.ForeignKey(blank=True, help_text='Target model for FK/O2O/M2M', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_relations', to='builder.clazz')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
                'ordering': ['clazz', 'order', 'name'],
                'unique_together': {('clazz', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, help_text='Optional description shown below the section title', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('collapsed', models.BooleanField(default=False, help_text='Render section collapsed by default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='builder.clazz')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['clazz', 'order', 'name'],
                'unique_together': {('clazz', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RelatedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_field', models.CharField(help_text='Name of the FK field on the child model that points back to the parent Clazz', max_length=100)),
                ('verbose_name', models.CharField(blank=True, help_text='Override inline heading', max_length=200)),
                ('inline_style', models.CharField(choices=[('tabular', 'Tabular (table rows)'), ('stacked', 'Stacked (form per row)')], default='tabular', max_length=10)),
                ('extra', models.PositiveIntegerField(default=1, help_text='Number of empty extra rows to show')),
                ('max_num', models.PositiveIntegerField(blank=True, help_text='Max rows allowed (blank = unlimited)', null=True)),
                ('fields_display', models.TextField(blank=True, help_text='Comma-separated fields to show in the inline (blank = all)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_clazz', models.ForeignKey(help_text='The child model shown as inline', on_delete=django.db.models.deletion.CASCADE, related_name='used_as_inline', to='builder.clazz')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_tables', to='builder.section')),
            ],
            options={
                'verbose_name': 'Related Table',
                'verbose_name_plural': 'Related Tables',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_fields', to='builder.field')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_fields', to='builder.section')),
            ],
            options={
                'verbose_name': 'Section Field',
                'verbose_name_plural': 'Section Fields',
                'ordering': ['order'],
                'unique_together': {('section', 'field')},
            },
        ),
    ]
